---
- hosts: localhost
  gather_facts: false
  become: false
  vars:
    ansible_python_interpreter: python3
    keycloak_url: "https://sso.{{ system_base_domain }}/auth"
    keycloak_validate_certs: no
    skip_internal_requests: "{{ lookup('env', 'UM_SKIP_INTERNAL_REQUESTS') == '0' }}"
    debug: "{{ lookup('env', 'DEBUG') == '1' }}"
    validate_certs: no
  tasks:
  - include_vars: /etc/unimatrix/defaults.yml
  - include_vars: /etc/unimatrix/unimatrix.yml

  # After an included playbook completes succesfully, we may assume
  # that the service is up and running.
  - name: included Keycloak provisioning tasks
    include: playbooks/keycloak.yml
    when: keycloak_enabled|default(False)

  - name: included GitLab provisioning tasks
    include: playbooks/gitlab.yml
    when: gitlab_enabled|default(False)

  - name: included Jenkins provisioning tasks
    include: playbooks/jenkins.yml
    when: jenkins_enabled|default(False)

  - name: included AWX provisioning tasks
    include: playbooks/awx.yml
    when: awx_enabled|default(False)
