- hosts: localhost
  gather_facts: false
  vars:
    keycloak_auth_realm: "{{ keycloak_realm|default('master') }}"
    keycloak_username: "{{ lookup('env', 'KEYCLOAK_USER') }}"
    keycloak_password: "{{ lookup('env', 'KEYCLOAK_PASSWORD') }}"
    keycloak_url: "{{ lookup('env', 'KEYCLOAK_URL') }}"
    keycloak_validate_certs: false
    c: "{{ saml_client }}"
  tasks:
  - name: create or update Keycloak client
    delegate_to: localhost
    keycloak_client:
      auth_client_id: admin-cli
      auth_keycloak_url: "{{ keycloak_url }}"
      auth_realm: "{{ keycloak_auth_realm }}"
      auth_username: "{{ keycloak_username }}"
      auth_password: "{{ keycloak_password }}"
      validate_certs: "{{ keycloak_validate_certs }}"
      state: present
      protocol: "{{ c.protocol }}"
      realm: "{{ c.realm }}"
      client_id: "{{ c.client_id }}"
      name: "{{ c.client_name }}"
      standard_flow_enabled: "{{ c.standard_flow_enabled }}"
      implicit_flow_enabled: "{{ c.implicit_flow_enabled }}"
      direct_access_grants_enabled: "{{ c.direct_access_grants_enabled }}"
      service_accounts_enabled: "{{ c.service_accounts_enabled }}"
      authorization_services_enabled: "{{ c.authorization_services_enabled }}"
      redirect_uris: "{{ c.redirect_uris }}"
      web_origins: "{{ c.web_origins }}"
      protocol_mappers: "{{ c.protocol_mappers|default([]) }}"
      attributes:
        saml.authnstatement: true
        saml.client.signature: false
        saml.force.post.binding: true
        saml.server.signature: true
        saml.signature.algorithm: RSA_SHA256
        saml.signing.certificate: "{{ lookup('file', '/var/run/secrets/saml/idp/tls.crt') }}"
        saml.signing.private.key: "{{ lookup('file', '/var/run/secrets/saml/idp/tls.key') }}"

        saml_force_name_id_format: "{{ c.attributes.saml_force_name_id_format|default('yes') }}"
        saml_name_id_format: "{{ c.attributes.saml_name_id_format|default('username') }}"
        saml_signature_canonicalization_method: "http://www.w3.org/2001/10/xml-exc-c14n#"
        user.info.response.signature.alg: RS256
        request.object.signature.alg: RS256
      full_scope_allowed: false
